# Generated by Django 5.0.4 on 2024-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not-started', 'Not Started'), ('reading', 'Reading'), ('completed', 'Completed')], default='not-started', max_length=20)),
            ],
        ),
    ]
