# Generated by Django 5.0.4 on 2024-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('not-started', 'Not started'), ('reading', 'Reading'), ('completed', 'Completed')], default='not-started', max_length=20),
        ),
    ]
