"""Initial migration

Revision ID: 3258fce49a0b
Revises: 
Create Date: 2024-05-14 17:23:29.494514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3258fce49a0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    # ### end Alembic commands ###
