# Generated by Django 5.0.6 on 2024-05-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated_date", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "file_attachments",
                    models.FileField(blank=True, upload_to="blog_attachments/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("images", models.ImageField(blank=True, upload_to="blog_images/")),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("links", models.ManyToManyField(blank=True, to="block.blog")),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_blogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subpages",
                    models.ManyToManyField(
                        blank=True, related_name="parent_blog", to="block.blog"
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="blog_tasks", to="block.task"
                    ),
                ),
            ],
        ),
    ]
