# Generated by Django 5.0.6 on 2024-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("block", "0003_birthday_post_alter_blogpost_title_event_movie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="post",
        ),
        migrations.AddField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
