# Generated by Django 5.0.6 on 2024-05-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("block", "0004_remove_movie_post_movie_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="post",
        ),
        migrations.AddField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
