# Generated by Django 5.0.6 on 2024-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("block", "0005_remove_event_post_event_id_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="event",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Deleted"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
    ]
