# Generated by Django 5.0.6 on 2024-05-24 05:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("block", "0006_alter_event_date_alter_event_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopping",
            name="post",
        ),
        migrations.AddField(
            model_name="shopping",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
